dist: xenial
language: go

go:
  - "1.12"

env:
  - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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

jobs:
  include:
    - stage: test
      script:
        - go test -cpu=1,2 -v ./...
    - script:
        - docker build -t concourse-slack-alert-resource-travis:$TRAVIS_BUILD_NUMBER .
        - echo "{\"source\":{\"url\":\"$SLACK_WEBHOOK_URL\"}}" | docker run -i
            -e "BUILD_TEAM_NAME=main"
            -e "BUILD_PIPELINE_NAME=travis-ci"
            -e "BUILD_JOB_NAME=test"
            -e "BUILD_NAME=$TRAVIS_BUILD_NUMBER"
            concourse-slack-alert-resource-travis:$TRAVIS_BUILD_NUMBER
            /opt/resource/out

branches:
  only:
    - master
